apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  selector:
    matchLabels:
      name: k8smaestro-webapp
  replicas: 3
  strategy:
    type: RollingUpdate # update strategy (default)
  template:
    metadata:
      labels:
        name: k8smaestro-webapp
    spec:
      containers:
      - name: webapp-ctr
        image: k8smaestro/web-app:2.0